helm:
  parameters:
  - name: frontend.image
    value: quith/frontend
    forcestring: true
  - name: frontend.tag
    value: main-f56b58f
    forcestring: true
  - name: backend.image
    value: quith/backend
    forcestring: true
  - name: backend.tag
    value: main-f56b58f
    forcestring: true
