frontend:
  image: quith/frontend
  tag: 'f56b58f'
  autoscaling:
    averageUtilization: 90
backend:
  image: quith/backend
  tag: 'f56b58f'
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
  
